-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 OpenLF2 contributors

-- Original mode IDs are stored in recordings.
return {
    modes = {
        versus = 0,
        stage = 1,
        championship = 2,
        team_championship = 3,
        battle = 4,
        demo = 5,
    },
    difficulties = {
        crazy = -1,
        difficult = 0,
        normal = 1,
        easy = 2,
    },
    stage_groups = {
        final_story = 4,
        survival = 5,
    },
    stage_levels = {
        survival_start = 50,
    },
    -- Kind 4 is catalog `type: 4`, used only by baseball; kind 6 is `type: 6`, used by milk
    -- and beer.
    record_kinds = {
        character = 0,
        light_item = 1,
        heavy_item = 2,
        ball = 3,
        baseball = 4,
        prisoner = 5,
        drink = 6,
    },
    -- A holder's `weapon` field normally repeats the held item's record_kinds value; knife
    -- and boomerang are the one documented exception.
    weapon_holder_codes = {
        knife_or_boomerang = 101,
    },
    -- Fighter record IDs from data/data.txt and object headers in the owner's
    -- v2.0a installer.
    fighter_ids = {
        template = 0,
        deep = 1,
        john = 2,
        henry = 4,
        rudolf = 5,
        louis = 6,
        firen = 7,
        freeze = 8,
        dennis = 9,
        woody = 10,
        davis = 11,
        bandit = 30,
        hunter = 31,
        mark = 32,
        jack = 33,
        sorcerer = 34,
        monk = 35,
        jan = 36,
        knight = 37,
        bat = 38,
        justin = 39,
        louis_ex = 50,
        firzen = 51,
        julian = 52,
    },
    record_ids = {
        criminal = 300,
        team_order_marker = 998,
    },
    -- Catalog boundaries used by original random fighter and weapon selection.
    record_id_ranges = {
        random_fighter_end_exclusive = 30,
        background_weapon_lower_exclusive = 99,
        background_weapon_end_exclusive = 200,
    },
    -- Special IDs in stage.dat entries.
    stage_record_selectors = {
        random_fighter = 1000,
        random_stage_enemy = 3000,
        random_stage_enemy_with_rare = 3001,
    },
    -- Frame state codes; special-state names follow the owner's v2.0a object frames.
    frame_states = {
        standing = 0,
        walking = 1,
        running = 2,
        attacking = 3,
        jumping = 4,
        dashing = 5,
        rowing = 6,
        defending = 7,
        broken_defend = 8,
        caught = 10,
        injured = 11,
        falling = 12,
        frozen = 13,
        lying = 14,
        dizzy = 16,
        drinking = 17,
        burning = 18,
        burning_run = 19,
        louis_dash_attack = 100,
        deep_dash_sword = 301,
        airborne_item = 1000,
        held_item = 1001,
        thrown_item = 1002,
        landed_light_item = 1003,
        resting_light_item = 1004,
        heal_self = 1700,
        flying_heavy_item = 2000,
        held_heavy_item = 2001,
        resting_heavy_item = 2004,
        flying_ball = 3000,
        ball_hiting = 3001,
        ball_hit = 3002,
        rebound_ball = 3003,
        object_disappearing = 3004,
        flying_missile = 3006,
        debris_piece = 9999,
        teleport_to_enemy = 400,
        teleport_to_ally = 401,
        transform_start = 500,
        transform_complete = 501,
        transform_louis_ex = 9995,
        louis_transform_shards = 9996,
        team_order_marker = 9997,
        removed = 9998,
    },
    -- States 8000–8999 encode the destination record as state - 8000.
    frame_state_ranges = {
        record_transform_start = 8000,
        record_transform_end_exclusive = 9000,
    },
    effects = {
        plain_hit = 0,
        sharp_hit = 1,
        burn = 2,
        freeze = 3,
        skip_characters = 4,
        burn_alt = 20,
        burn_state_guard = 21,
        burn_push = 22,
        burn_sound = 23,
        rebound = 30,
    },
    hit_fa_modes = {
        chase = 1,
        animated_chase = 2,
        projectile_chase = 3,
        healing_projectile = 4,
        ally_projectiles = 5,
        enemy_seeker = 6,
        returning_copy = 7,
        multi_seeker = 8,
        ranged_attack = 9,
        accelerating = 10,
        explosion = 11,
        unanimated_chase = 12,
        single_seeker = 13,
        special_chase = 14,
    },
    teleport_modes = {
        nearest_enemy = 1,
        farthest_ally = 2,
    },
    hit_list_results = {
        not_listed = 0,
        list = 1,
        skip = 2,
    },
    attack_kinds = {
        plain = 0,
        catch_nearest = 1,
        pick_up = 2,
        catch = 3,
        thrown_body = 4,
        held_item = 5,
        super_window = 6,
        rolling_pickup = 7,
        heal = 8,
        reflect_ball = 9,
        whirlwind = 10,
        conditional_whirlwind = 11,
        ignored_12 = 12,
        ignored_13 = 13,
        obstacle = 14,
        pulling_whirlwind = 15,
        freezing_whirlwind = 16,
    },
    cpoint_kinds = {
        holder = 1,
        caught = 2,
    },
    stage_entry_kinds = {
        soldier = 1,
        boss = 2,
    },
    -- opoint kind 1 is the ordinary (detached) spawn, the majority case in the owner's v2.0a
    -- catalog; it needs no special-case code beyond the kind > 0 spawn gate.
    opoint_kinds = {
        normal = 1,
        held_spawn = 2,
    },
    -- wpoint kinds 1 and 2 behave identically; only kind 3 (drop) changes behavior, so this
    -- may be an authoring-only distinction.
    wpoint_kinds = {
        primary = 1,
        secondary = 2,
        drop = 3,
    },
    recording_statuses = {
        starting = 1,
        saved = 2,
        cancelled = 3,
        error = 4,
    },
    teams = {
        independent = 0,
        player_one = 1,
        player_two = 2,
        player_three = 3,
        player_four = 4,
        enemies = 5,
        active_end_exclusive = 40,
    },
    item_ids = {
        stick = 100,
        hoe = 101,
        knife = 120,
        baseball = 121,
        boomerang = 124,
        stone = 150,
        wooden_box = 151,
        louis_armour = 217,
        louis_armour_two = 218,
        milk = 122,
        beer = 123,
        ice_sword = 213,
    },
    -- Names follow data/data.txt in the local v2.0a installer and the corresponding
    -- object files.
    object_ids = {
        john_ball = 200,
        henry_arrow = 201,
        rudolf_weapon = 202,
        deep_ball = 203,
        henry_wind = 204,
        dennis_ball = 205,
        woody_ball = 206,
        davis_ball = 207,
        henry_arrow_two = 208,
        freeze_ball = 209,
        firen_ball = 210,
        firen_flame = 211,
        freeze_column = 212,
        john_biscuit = 214,
        dennis_chase = 215,
        jack_ball = 216,
        jan_ally_chase = 219,
        jan_chase = 220,
        firzen_chase_fire = 221,
        firzen_chase_ice = 222,
        firzen_ball = 223,
        bat_ball = 224,
        bat_chase = 225,
        justin_ball = 226,
        julian_ball = 228,
        julian_ball_two = 229,
        broken_weapon = 999,
    },
}
